// Dummy Tables Data
export const dummyTables = [
  {
    id: 1,
    name: 'Table 1',
    type: 'Standard',
    status: 'Available',
    capacity: 4,
    hourlyRate: 150,
    description: 'Standard billiards table with professional felt and accessories.',
    image: '/images/standard-table.jpg',
  },
  {
    id: 2,
    name: 'Table 2',
    type: 'Standard',
    status: 'Occupied',
    capacity: 4,
    hourlyRate: 150,
    description: 'Standard billiards table with professional felt and accessories.',
    image: '/images/standard-table.jpg',
  },
  {
    id: 3,
    name: 'Table 3',
    type: 'Standard',
    status: 'Available',
    capacity: 4,
    hourlyRate: 150,
    description: 'Standard billiards table with professional felt and accessories.',
    image: '/images/standard-table.jpg',
  },
  {
    id: 4,
    name: 'Table 4',
    type: 'Standard',
    status: 'Reserved',
    capacity: 4,
    hourlyRate: 150,
    description: 'Standard billiards table with professional felt and accessories.',
    image: '/images/standard-table.jpg',
  },
  {
    id: 5,
    name: 'VIP Table 1',
    type: 'VIP',
    status: 'Available',
    capacity: 6,
    hourlyRate: 250,
    description: 'VIP table in a private area with premium amenities and service.',
    image: '/images/vip-table.png',
  },
  {
    id: 6,
    name: 'VIP Table 2',
    type: 'VIP',
    status: 'Occupied',
    capacity: 6,
    hourlyRate: 250,
    description: 'VIP table in a private area with premium amenities and service.',
    image: '/images/vip-table.png',
  },
  {
    id: 7,
    name: 'VIP Table 3',
    type: 'VIP',
    status: 'Available',
    capacity: 6,
    hourlyRate: 250,
    description: 'VIP table in a private area with premium amenities and service.',
    image: '/images/vip-table.png',
  },
  {
    id: 8,
    name: 'VIP Table 4',
    type: 'VIP',
    status: 'Maintenance',
    capacity: 6,
    hourlyRate: 250,
    description: 'VIP table in a private area with premium amenities and service.',
    image: '/images/vip-table.png',
  },
  {
    id: 9,
    name: 'Premium Table 1',
    type: 'Premium',
    status: 'Available',
    capacity: 8,
    hourlyRate: 350,
    description: 'Top-tier tournament-grade table with the finest materials and setup.',
    image: '/images/premium-table.png',
  },
  {
    id: 10,
    name: 'Premium Table 2',
    type: 'Premium',
    status: 'Available',
    capacity: 8,
    hourlyRate: 350,
    description: 'Top-tier tournament-grade table with the finest materials and setup.',
    image: '/images/premium-table.png',
  },
];

// Dummy Bookings Data
export const dummyBookings = [
  {
    id: 1,
    referenceNumber: 'CR-2024-001',
    userId: 2,
    userName: 'John Doe',
    userEmail: 'john@example.com',
    tableId: 1,
    tableName: 'Table 1',
    date: '2024-12-05',
    startTime: '14:00',
    duration: 2,
    totalAmount: 300,
    paymentMethod: 'Cash',
    status: 'Confirmed',
  },
  {
    id: 2,
    referenceNumber: 'CR-2024-002',
    userId: 2,
    userName: 'John Doe',
    userEmail: 'john@example.com',
    tableId: 5,
    tableName: 'VIP Table 1',
    date: '2024-12-10',
    startTime: '18:00',
    duration: 3,
    totalAmount: 750,
    paymentMethod: 'GCash',
    status: 'Pending',
  },
  {
    id: 3,
    referenceNumber: 'CR-2024-003',
    userId: 3,
    userName: 'Jane Smith',
    userEmail: 'jane@example.com',
    tableId: 9,
    tableName: 'Premium Table 1',
    date: '2024-11-20',
    startTime: '15:00',
    duration: 2,
    totalAmount: 700,
    paymentMethod: 'Cash',
    status: 'Completed',
  },
  {
    id: 4,
    referenceNumber: 'CR-2024-004',
    userId: 2,
    userName: 'John Doe',
    userEmail: 'john@example.com',
    tableId: 3,
    tableName: 'Table 3',
    date: '2024-11-15',
    startTime: '10:00',
    duration: 1,
    totalAmount: 150,
    paymentMethod: 'GCash',
    status: 'Cancelled',
  },
];

// Dummy Users Data
export const dummyUsers = [
  {
    id: 2,
    name: 'John Doe',
    email: 'john@example.com',
    phone: '09123456789',
    role: 'customer',
    joinedDate: '2024-01-15',
  },
  {
    id: 3,
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '09234567890',
    role: 'customer',
    joinedDate: '2024-02-20',
  },
  {
    id: 4,
    name: 'Bob Johnson',
    email: 'bob@example.com',
    phone: '09345678901',
    role: 'customer',
    joinedDate: '2024-03-10',
  },
];

// Dummy Admin Stats
export const dummyStats = {
  todayBookings: 12,
  currentOccupancy: 5,
  totalTables: 10,
  pendingCheckouts: 3,
  todayRevenue: 4500,
  weekRevenue: 28000,
  monthRevenue: 95000,
};
